In [70]:
import pandas as pd
import numpy as np
from scipy.stats import percentileofscore
from sklearn.preprocessing import StandardScaler
import pickle
import os
from preprocessed_data_streamlit import df,df_scaled, features, sorted_states, sorted_counties, racial_features, get_pool_and_scaled
from streamlit_aip import plot_df,selected_data,map_data,top_10_counties

In [71]:
# dtype object
df['Latitude'].dtype

# optional: Python type of the dtype object and its string name
type(df['Latitude'].dtype)
df['Latitude'].dtype.name

'float64'

In [72]:
df[['Latitude','Longitude']].isnull().sum()
top_10_counties[['Latitude','Longitude']].isnull().sum()

Latitude     0
Longitude    0
dtype: int64

In [73]:
# ... your existing imports and data loading ...
def check_county(df, state_name, county_name_partial):
    county_check = df[(df['State'] == state_name) & (df['County'].str.contains(county_name_partial))]
    if county_check.empty:
        print(f"{county_name_partial} County not found in {state_name}!")
        return pd.DataFrame()
    county_check['County_name'] = county_check['County'].str.replace(r'<.*?>', '', regex=True)
    return county_check[['County', 'County_name', 'Latitude', 'Longitude', 'FIPS']]

# Check Oglala Lakota County
check_county(df, 'South Dakota', 'Oglala Lakota')

C:\Users\miket\AppData\Local\Temp\ipykernel_2080\189181825.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  county_check['County_name'] = county_check['County'].str.replace(r'<.*?>', '', regex=True)

             County    County_name  Latitude  Longitude   FIPS
2413  Oglala Lakota  Oglala Lakota       NaN        NaN  46102

In [76]:
oglala_coords = df.loc[df['County'] == 'Oglala Lakota', ['County', 'Latitude', 'Longitude']]
oglala_coords

             County  Latitude  Longitude
2413  Oglala Lakota       NaN        NaN

In [82]:


data = pd.read_csv('C:/Users/miket/OneDrive/Desktop/streamlit_aip/data/data.csv')
oglala_coords = data.loc[df['County'] == 'Oglala Lakota', ['County', 'Latitude', 'Longitude']]
oglala_coords

             County  Latitude  Longitude
2413  Oglala Lakota   43.2437   102.6205